[build]
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

# Use the official Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase timeout for file processing
  timeout = 30

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.cerebras.ai;" 